### ISSUE TITLE
Change tbp to tpb (thepiratebay)

### ISSUE THREAD

**Issue by win32re** [frostwire/frostwire-desktop#419]
'tbp' should be changed 'tpb' (thepiratebay, not thebaypirate) in file
https://github.com/frostwire/frostwire-desktop/blob/master/src/com/limegroup/gnutella/gui/search/SearchEngine.java#L35

**Comment by win32re** [comment]
@gubatron what files should be changed to reflect this change?

**Comment by gubatron** [comment]
wow good catch!, the whole folder needs to be renamed, I'll do that very easily with my editor.

**Comment by gubatron** [comment]
fixed here and on frostwire-common.

Thanks.
