### ISSUE TITLE
Launch FrostWire on Startup not working

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire-desktop#447]
>"I got brave and turned on the option to have FW auto-start with system start up. It didn't.
Using msconfig and Program Manager, I examined all the places that System Start Up looks to see what needs to be started. FW was nowhere to be found." -Zooky

http://forum.frostwire.com/viewtopic.php?f=1&t=23701

I've labeled as high-priority as this feature greatly increases the chances for more upload bandwidth on the p2p network.

## $25 BOUNTY
There's a $25 bounty to be paid in Bitcoin to the collaborator that manages to send a patch we can merge with this fix.

**Comment by win32re** [comment]
@gubatron check pr #449, it fixes the issue

**Comment by gubatron** [comment]
checking!

**Comment by gubatron** [comment]
testing on windows @win32re now.

**Comment by gubatron** [comment]
ok, it works.
Will merge and fix so that the value is not hardcoded and we don't break when we go to FrostWire 7.

Please give me a Bitcoin address to send your bounty today.

**Comment by gubatron** [comment]
@muckachina please make this a test case.
"Make sure FrostWire will autostart on Windows if the user has marked that setting."

**Comment by muckachina** [comment]
This is already an opened issue, are you talking about this https://github.com/frostwire/qa-desktop/issues/63 ?

**Comment by win32re** [comment]
@gubatron 12wHNF7sqcntUK8PwyEQmRDekFdAVw1gGC
Thanks!

**Comment by win32re** [comment]
@gubatron I tried to use the version variable but I still have to figure out how to extract the first letter from a string. The variable contains multiple version digits (6.x.x).

**Comment by gubatron** [comment]
bounty on frostwire-desktop issue #447 ($25 @ 1 BTC = $248.16) paid:
[Bitcoin Transaction a7b4483727d89848dd4be950d37daabc6b5c5548209fc9df83d3b8778e0ed35f](https://blockchain.info/tx/a7b4483727d89848dd4be950d37daabc6b5c5548209fc9df83d3b8778e0ed35f)

**Comment by win32re** [comment]
Thanks!

**Comment by muckachina** [comment]
I tested re-starting and also shutting down my Mac with the option "Run on System startup" selected and nothing happened, FrostWire has not being launched automatically when the System starts.

Running FrostWire 6.0.7 on Yosemite 10.10.2

Testing now on Windows

**Comment by gubatron** [comment]
yes, that's a separate bug :)

Want to fix it for MacOSX @win32re ?

**Comment by muckachina** [comment]
Tested on Windows Vista and worked fine, the app opened automatically after re-starting the system, however on Windows 8 tablet doesn't work, FrostWire doesn't open automatically when opening desktop right after the system starts.

On Windows XP there is not an option to start FrostWire when the system start.

**Comment by gubatron** [comment]
very good find @muckachina (let's not worry about XP, probably has been this way because XP doesn't support this at all, too old)

we have to see what the mechanism is for windows 8 then.
