### ISSUE TITLE
Delayed auto start when in silent mode

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire-desktop#458]
Feature requested by InstallCore to delay the auto-start of FrostWire when in silent mode. It would be great if it would be a passable parameter so they can control the delay time. They requested 3-5 min after install.

**Comment by gubatron** [comment]
Preliminar feature idea will be as follows, possible technical limitations aside.

**User will be able to use the auto-start delay feature only when `/S` (silent mode) is present.**

For example, delaying 15 seconds would be invoked as follows 
with the new `/DELAY_AUTO_START <milliseconds>` parameter:
 
```
frostwire-windows-x.y.z.exe /S /FPC partnerCodeHere /DELAY_AUTO_START 15000
```
