### ISSUE TITLE
frostwire.dmg infected with PUA.OSX.InstallCore

### ISSUE THREAD

**Issue by johnblommers** [frostwire/frostwire-desktop#462]
After downloading frostwire.dmg v6.1.3 my ClamXav sentry scans it and reports it is infected with PUA.OSX.InstallCore. According to AVG:

"InstallCore is a software that installs an additional program to display and/or download to your device unwanted advertisements, toolbars and may be considered privacy-invasive. These kinds of threats, called Adware, track your computer's web usage to feed you undesired ad pop-ups and some might even hijack your browser start or search pages, redirecting you to a different site or search engine than the one you had originally configured.InstallCore is currently ranked 22 in the world of online malware."

Sorry but Adware is not something I want installed on my Macintosh. It should have been made clear that this was going to happen. I should not have discovered this after the fact.

Please remove the Adware from Frostwire. What a shame to encumber the software this way.

**Comment by gubatron** [comment]
thank you for reporting this. we'll take it to InstallCore and see why they've been flagged by AVG asap.

Thanks!

CC: @kad3mlia
